server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
spring:
  datasource:
    hikari:
      maximumPoolSize: 20
      max-active: 20
      max-idle: 10
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/
    username: postgres
    password: 123
  jpa:
    databasePlatform: org.hibernate.dialect.PostgreSQL9Dialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${NZ_EMAIL:''}
    password: ${NZ_PASSWORD:''}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
      test-connection: true
flyway:
  locations: filesystem:db/migration
  password: 123
  url: jdbc:postgresql://localhost:5432/
  user: postgres
nz:
  allowed:
    origin: '*'
  jwt:
    secret: secretofdonossousjwt
    expiration: 86400000