server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
spring:
  profiles:
    active: dev
  datasource:
    hikari:
      maximumPoolSize: 20
      max-active: 20
      max-idle: 10
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
    driverClassName: org.postgresql.Driver
    url: $JDBC_DATABASE_URL
    username: $JDBC_DATABASE_USERNAME
    password: $JDBC_DATABASE_PASSWORD
  jpa:
    databasePlatform: org.hibernate.dialect.PostgreSQL9Dialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${NZ_EMAIL:''}
    password: ${NZ_PASSWORD:''}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
      test-connection: true
flyway:
  locations: filesystem:db/migration
  password: $JDBC_DATABASE_PASSWORD
  url: jdbc:h2:mem:DATABASE
  user: $JDBC_DATABASE_USERNAME
nz:
  allowed:
    origin: '*'
  jwt:
    secret: $JWT_SECRET
    expiration: 86400000